### Create a new post（Need token）
POST http://localhost:5000/api/posts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4MjBhNDhkNTczNTU1MGJkNDNiZTY4MCIsInVzZXJuYW1lIjoidGVzdHVzZXIxIiwiaWF0IjoxNzQ3MTQyNTgxLCJleHAiOjE3NDcxNDYxODF9.w4RSH2hMjmtCHbgNOuJmJClUTCY9gjMoEofmoKjEOiA

{
  "title": "My Second Blog Post",
  "content": "This is the content of my second post."
}

### Get all posts
GET http://localhost:5000/api/posts

### Get a single post
GET http://localhost:5000/api/posts/682347d066257ada0ecdf746
